server:
  port : 8080

spring:
  liquibase.enabled: false
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:tradeStoreDB
    driverClassName: org.h2.Driver
    username: cibtest
    password: password
    initialization-mode: never
test.cib.validation.enabled: true
test.cib.expiry.job.start-time: '0 0 20 * * ?'
